### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Imper7302/PragmatechFoundationProject#1]
_Mətləb, reponuzu ümumi analiz etdim və yanlış olduğunu fikirləşdiyim bəzi məqamlar var. Məsələn, commit mesajları düzgün deyil. Repoya "README" faylı əlavə etsəniz və gördüyünüz işləri də oraya qeyd etsəniz yaxşı olar. Css faylları "css" adlı qovluqda olmalıdır, şəkillər isə "img" adlı qovluqda ola bilər, yəni mütləq başqa bir qovluqda olmalıdır. Daha çox px yox, em və rem kimi ölçü vahidlərindən istifadə edilsə əla olar (responsivlikdə də kömək olar). Demək olar ki, hər gün GitHuba işlərinizi push edirsiniz, bu yaxşı haldır. Uğurlar!🙂_

**Comment by Imper7302** [comment]
Oldu çox sağoun. Bütün çatışmamazlıqları aradan qaldırmaqa çalışacam. Bəs
commitləri necə adlandırsam düzgün olar?

14 Kas 2021 Paz 14:18 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
_Bu [məqaləni](https://serdarkuzucu.com/2020/04/19/git-commit-mesaji-nasil-yazilmali/) analiz edin, zəhmət olmasa._
