### ISSUE TITLE
".html" uzantılı faylları ayrıca qovluğa salmağa ehtiyac yoxdur

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Imper7302/PragmatechFoundationProject#11]
**[Bu](https://github.com/Imper7302/PragmatechFoundationProject/tree/master/ProjectFrontEnd/qarantkredit)** hissədə index.html faylını "html" adlı qovluğa salmısınız, düzgün deyil, ".html" uzantılı faylları ayrıca qovluğa salmağa ehtiyac yoxdur. **[Bu](https://openlab.bmcc.cuny.edu/mmp-240-fall-19-stein/2019/09/05/basic-website-folder-file-structure)** qaynaq faydalı ola bilər.

**Comment by Imper7302** [comment]
Aha ederem.
