### ISSUE TITLE
Bütün teqlərə class adı verməyə çalışın 

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Imper7302/PragmatechFoundationProject#12]
**[Bu](https://github.com/Imper7302/PragmatechFoundationProject/blob/master/ProjectFrontEnd/qarantkredit/css/style.css#L62)** hissədə `.navbar-list ul li a` yazmaq yerinə `a` teqinə class adı vermək daha oxunaqlı olmaz, sizcə? Məncə, elə olar. Məsələn, `nav-link` və ya elə adicə `link` adında class adı verə bilərsiniz. Həm yazılışı daha qısa olduğu üçün daha oxunaqlı olar, həm də bu class'dan başqa yerdə də istifadə edə bilərsiniz. Elə ən əsası da budur. Başqa yerdə istifadə edə bilmək.

**Comment by Imper7302** [comment]
Aaa duz deyirsiz burasini, bu gun bunun eziyyetini cekmiwik, heec burasini fikirlewmemiwdik. Coox tesekkur.

**Comment by isbendiyarovanezrin** [comment]
Xoşdur.🙂

**Comment by Imper7302** [comment]
bu gun başa düşdükki niyə taqlara ad vermeyimizi tələb edirdiz), o biri lahiyələrdə mütləü edəcəyiz.

**Comment by isbendiyarovanezrin** [comment]
Əla!🙂
