### ISSUE TITLE
"README.md" faylından istifadə edin 

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Imper7302/PragmatechFoundationProject#15]
"README.md" faylında gördüyünüz işlərlə bağlı məlumat verə bilərsiniz. **[Bu](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)** qaynaq faydalı ola bilər.

**Comment by Imper7302** [comment]
Onu bacarmiram)

**Comment by Imper7302** [comment]
Ne yazim bilmiremki,)

**Comment by isbendiyarovanezrin** [comment]
Nümunə olaraq mənimkilərə baxa bilərsiniz. 
- [**Birinci README**](https://github.com/isbendiyarovanezrin/PragmatechFrontendProject#readme) 
- [**İkinci README**](https://github.com/isbendiyarovanezrin/PragmatechFoundationProject#readme)

**Comment by isbendiyarovanezrin** [comment]
Kodlarına da baxa bilərsiniz.
