### ISSUE TITLE
<header> teqindən istifadə edin 

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Imper7302/PragmatechFoundationProject#16]
`<div id="header"> . . . </div>` kimi yazmaqdansa `<header></header>` teqindən istifadə edə bilərsiniz. Teq haqqında daha ətraflı **[bu](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header)** qaynaqdan oxuya bilərsiniz.

**Comment by Imper7302** [comment]
Oldu
