### ISSUE TITLE
<nav> teqindən düzgün istifadə edin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Imper7302/PragmatechFoundationProject#17]
Əgər `<nav>` teqindən istifadə etmisinizsə bunu `<div class="nav-navbar"> . . . </div>` yazmağa ehtiyac yoxdur (sırf sizin kodunuza əsasən yazmışam bu cümləni). Teq haqqında daha ətraflı **[bu](https://www.w3schools.com/tags/tag_nav.asp)** qaynaqdan oxuya bilərsiniz.

**Comment by Mehemmed0330** [comment]
bu teqin islenmesi ul li kimi dusunun.Yeni nece ki bunlari verdikden sonra class adi veririk eyni formada da nav a tetbiq etmek olar

**Comment by isbendiyarovanezrin** [comment]
Məhəmməd, mən sırf Mətləbin koduna əsasən yazmışam. Təbii ki, `<nav>` teqindən istifadə edilibsə bu `<div class="nav-navbar"></div>` şəkildə kod yazıla bilər. Əsasən "navbar-nav" class'ını `ul`, `li` hissəsini yazanda `ul` teqinə verirlər (aşağıda nümunə var). Kodda isə ümumisinə o ad verilib. Burada olan əsas məsələ class adıdır. Ona görə də yazmışam ki, bu `<div class="nav-navbar"></div>` teqi yazmağa ehtiyac yoxdur (əslində o hissəni çox da düz qeyd etməmişəm, bu class adında div verilməsə olar, amma div teqi yazıla bilər əlbəttə), çünki onsuz da bu class adı səhv yerdə verilib və onun içində olan hər şey də başqa bir divin içindədir (həmin divə başqa class adı verilsəydi yenə də bir şey deməzdim, amma "navbar-nav" class adını görəndə `ul` teqinə verildiyini düşünürəm). Ümumi class adlarını sevmədiyim üçün və hər şey `nav` teqinin içində yazıldığı üçün yazdım ki, "`<nav>` teqindən düzgün istifadə edin". Ümid edirəm başa sala bildim. Mətləb, **[bu](https://getbootstrap.com/docs/5.1/components/navbar)** qaynaqdakı kodlara fikir verin və bundan sonra düzgün class adlarından istifadə etməyə çalışın.

```html
<ul class="navbar-nav">
  <li class="nav-item">
    <a class="nav-link active" href="#">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Features</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Pricing</a>
  </li>
</ul>
```

_Kodları Bootstrap'ın səhifəsindən götürmüşəm._
