### ISSUE TITLE
Boş faylları, qovluqları ya repodan silin ya da içini doldurun

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Imper7302/PragmatechFoundationProject#3]
- [Bu](https://github.com/Imper7302/PragmatechFoundationProject/tree/master/Works/standart) qovluğun içi boşdur, silinsə yaxşı olar. 
- [Bu](https://github.com/Imper7302/PragmatechFoundationProject/tree/master/Works/week04day03) qovluqda içində şəkillər olan iki qovluq var. Biri bəsdir, "wireframe" adında olanı silin, məncə. 
- README faylının məqsədini səhv başa düşmüsünüz, deyəsən. [Bu](https://www.mygreatlearning.com/blog/readme-file/) məqaləyə göz gəzdirin, zəhmət olmasa.

**Comment by Imper7302** [comment]
Men standart papka yaratmiwam, yeni tapwiriq papkasi yaradan kimi ctrl+c ctrl+v edib atiram.

**Comment by isbendiyarovanezrin** [comment]
Bunun mənim dediklərim ilə nə əlaqəsi var?
