### ISSUE TITLE
<nav> teqindən istifadə edin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Imper7302/PragmatechFoundationProject#6]
[Bu](https://github.com/Imper7302/PragmatechFoundationProject/blob/master/Works/week05day03/html/index.html#L14) hissədə `<section id="navbar"> . . . </section>` teqindən istifadə etməkdənsə birbaşa `<nav></nav>` teqindən istifadə edə bilərsiniz. Teq haqqında daha ətraflı [bu](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav) qaynaqdan oxuya bilərsiniz.

**Comment by Imper7302** [comment]
Cox sagol, oxuyaram.
Umumilikde necedi yazilim?, neyise deyiwmeye ehtiyac var? Css terefinede baxardin zehmet olmasa.

**Comment by isbendiyarovanezrin** [comment]
Məsələn, [bu](https://github.com/Imper7302/PragmatechFoundationProject/blob/master/Works/week05day03/html/index.html) hissədə olan kodların düzülüşü səliqəsizdir, oxunaqlı deyil. Baxan kimi nə nəyin içindədir və s. tam başa düşmək olmur.

**Comment by isbendiyarovanezrin** [comment]
Visual Studio Code'də "Prettier - Code formatter" adlı extension var. Kodları səliqəyə salır. Ondan mütləq istifadə edin. Hər dəfə kodları yadda saxlayanda özü avtomatik olaraq səliqəyə salır.

**Comment by Imper7302** [comment]
Oldu ederem, bunu da font googledan atmiwam fikir vermemiwem)
