### ISSUE TITLE
rem və em kimi ölçü vahidlərindən istifadə edin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Imper7302/PragmatechFoundationProject#9]
[Bu](https://github.com/Imper7302/PragmatechFoundationProject/blob/master/ProjectFrontEnd/qarantkredit/css/style.css) hissədə demək olar ki, ancaq `px` ölçü vahidindən istifadə etmisiniz. Çalışın `rem` və `em` kimi ölçü vahidlərindən də istifadə edin. Faydalı ola biləcək qaynaqlar: 
- [Birinci qaynaq](https://youtu.be/f9dsxnRoihY)
- [İkinci qaynaq](https://www.freecodecamp.org/news/css-unit-guide)
- [Üçüncü qaynaq](https://www.digitalocean.com/community/tutorials/css-rem-vs-em-units)
- [Dördüncü qaynaq](https://www.w3schools.com/cssref/css_units.asp)
- [Beşinci qaynaq](https://css-tricks.com/fun-viewport-units)
- [Altıncı qaynaq](https://youtu.be/FgOTldP0eqk)
- [Yeddinci qaynaq](https://medium.com/@hossam.hilal0/rem-vs-em-units-in-css-96d5ac15878e)

**Comment by Imper7302** [comment]
ele xeyyamla daniwdiq bu barede, ama hec vermemiwik deyene dedik bildiyimiz kimi verek, sonra deyiwerik mehemmedle sizin komeyinizle. bele yazib sonra deyiwmek mumkun sonra?problem olmurki?
bu qaynaqlarida dersden sonra oxuyacam, cox sagolun.

**Comment by isbendiyarovanezrin** [comment]
Bəli, dəyişə bilərsiniz, amma vaxt alacaq. Ona görə də əvvəlcədən bu cür yazılsa daha yaxşı olar.

**Comment by Imper7302** [comment]
bu axwam bu catiwmazligi caliwib aradan qaldiracayiq, mumkun olmasa sabah sizden komeklik alacayiq)

**Comment by isbendiyarovanezrin** [comment]
Linklərdəki qaynaqlarda hər şey ətraflı yazılıb. Biz də deyəndə bu qaynaqlardan baxıb, oxuyub deyirik. Diqqətlə oxusanız əminəm ki, özünüz edə bilərsiniz. Bilməsəniz də kömək edərik. :)

**Comment by Imper7302** [comment]
yani men istifade etmemiwem umumilikde), yenede caliwib ozumuz edeceyik)
